// mock模拟数据
import Mock from 'mockjs'

// 图表数据
let List = []
export default {
  getStatisticalData: () => {
    for(let i=0;i<7;i++){
      List.push(
        Mock.mock({
          华为:Mock.Random.float(100,8000,0,0),
          vivo:Mock.Random.float(100,8000,0,0),
          oppo:Mock.Random.float(100,8000,0,0),
          魅族:Mock.Random.float(100,8000,0,0),
          三星:Mock.Random.float(100,8000,0,0),
          小米:Mock.Random.float(100,8000,0,0),
        })
      )
    }
    return {
      code:20000,
      data:{
        // 饼状图
        videoData:[
          {
            name:'小米',
            value:2999
          },
          {
            name:'apple',
            value:5999
          },
          {
            name:'vivo',
            value:1500
          },
          {
            name:'oppo',
            value:1999
          },
          {
            name:'魅族',
            value:2200
          },
          {
            name:'三星',
            value:6999
          }
        ],
        // 柱状图
        userData:[
          {
            data:'周一',
            new:5,
            active:200
          },
          {
            data:'周二',
            new:10,
            active:500
          },
          {
            data:'周三',
            new:12,
            active:550
          },
          {
            data:'周四',
            new:60,
            active:800
          },
          {
            data:'周五',
            new:65,
            active:550
          },
          {
            data:'周六',
            new:53,
            active:770
          },
          {
            data:'周日',
            new:33,
            active:170
          },
        ],
        // 折线图
        orderData:{
          date:['20220606','20220607','20220608','20220609','20220610','20220611','20220612'],
          data:List
        },
        tableData:[
          {
            name:'oppo',
            todayBuy:500,
            monthBuy:3500,
            totalBuy:22000
          },
          {
            name:'vivo',
            todayBuy:300,
            monthBuy:2200,
            totalBuy:24000
          },
          {
            name:'apple',
            todayBuy:800,
            monthBuy:4500,
            totalBuy:65000
          },
          {
            name:'小米',
            todayBuy:1200,
            monthBuy:3500,
            totalBuy:21000
          },
          {
            name:'魅族',
            todayBuy:300,
            monthBuy:2100,
            totalBuy:12000
          },
          {
            name:'三星',
            todayBuy:1000,
            monthBuy:6500,
            totalBuy:32000
          }
        ]
      }
    }
  }
}